-- ============================================================================
-- Categories keep the order they were created in.
--
-- The category lists were ordered by `name`, which hands the order to the
-- database's collation: capitals before lowercase under a byte-order locale,
-- Chinese names by code point rather than by anything a reader would
-- recognise, and "Other" filed alphabetically into the middle of the list.
-- The JSON store this replaced kept each list in insertion order -- the seed
-- list as written, with anything added appended after it -- and that is the
-- order people had been looking at.
--
-- sort_order restores that. It is an identity column, so every new category
-- takes the next value and lands at the bottom; a rename is an UPDATE and
-- keeps its place. Values are shared across users, which does not matter:
-- only their order within one person's list is ever used.
-- ============================================================================

alter table public.categories add column sort_order bigint;

-- --- Backfill ----------------------------------------------------------------
-- Categories have no created_at, so the original insertion order cannot be
-- read back. It can be rebuilt: every account was seeded by handle_new_user(),
-- in one of the two lists below, and everything else was added afterwards.
-- So seeded names first, in seed order, then the rest. The rest are sorted by
-- name as a best guess -- and so is a seeded category that has since been
-- renamed, since its new name no longer matches the list.
with seeds (kind, name, ord) as (
    select 'expense', name, ord from unnest(array[
        'Food & Drink', 'Shopping', 'Transport', 'Bills & Utilities',
        'Entertainment', 'Health', 'Groceries', 'Installments', 'Other'
    ]) with ordinality as t(name, ord)
    union all
    select 'expense', name, ord from unnest(array[
        '餐饮', '购物', '交通', '水电杂费', '娱乐', '医疗', '日用采买', '分期付款', '其他'
    ]) with ordinality as t(name, ord)
    union all
    select 'income', name, ord from unnest(array[
        'Salary', 'Investments', 'Gifts', 'Refunds', 'Other'
    ]) with ordinality as t(name, ord)
    union all
    select 'income', name, ord from unnest(array[
        '工资', '投资', '礼金', '退款', '其他'
    ]) with ordinality as t(name, ord)
),
ranked as (
    select c.id,
           row_number() over (
               order by c.user_id, c.kind,
                        s.ord is null,     -- seeded names ahead of added ones
                        s.ord,
                        lower(c.name), c.id
           ) as position
      from public.categories c
      left join seeds s on s.kind = c.kind and s.name = c.name
)
update public.categories c
   set sort_order = r.position
  from ranked r
 where r.id = c.id;

alter table public.categories alter column sort_order set not null;
alter table public.categories
    alter column sort_order add generated by default as identity;

-- Start new categories after the backfilled ones, or the first few added
-- would be numbered 1, 2, 3... and jump to the top of the list.
select setval(pg_get_serial_sequence('public.categories', 'sort_order'),
              greatest((select max(sort_order) from public.categories), 1));

-- --- Seeding -----------------------------------------------------------------
-- Replaces 20260910160000's version. Identical except for `with ordinality`
-- and `order by`: the identity values are handed out in the order the rows
-- arrive, and without an ORDER BY that order is not something Postgres
-- promises, however reliably unnest happens to produce it today.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    -- Only the language matters here; a 'zh-Hant' or 'zh-CN' still means the
    -- Chinese list, and the app only ships Simplified.
    wants_chinese boolean :=
        left(coalesce(new.raw_user_meta_data ->> 'locale', ''), 2) = 'zh';
begin
    insert into public.profiles (id, display_name)
    values (
        new.id,
        -- Supabase puts whatever the sign-up form sent in raw_user_meta_data.
        -- Falling back to the local part of the email means the greeting is
        -- never blank, even for an account created without a name.
        coalesce(
            nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''),
            split_part(new.email, '@', 1)
        )
    );

    insert into public.categories (user_id, kind, name)
    select new.id, 'expense', name
    from unnest(
        case when wants_chinese then array[
            '餐饮',
            '购物',
            '交通',
            '水电杂费',
            '娱乐',
            '医疗',
            '日用采买',
            '分期付款',
            '其他'
        ] else array[
            'Food & Drink',
            'Shopping',
            'Transport',
            'Bills & Utilities',
            'Entertainment',
            'Health',
            'Groceries',
            'Installments',
            'Other'
        ] end
    ) with ordinality as t(name, ord)
    order by ord;

    insert into public.categories (user_id, kind, name)
    select new.id, 'income', name
    from unnest(
        case when wants_chinese then array[
            '工资',
            '投资',
            '礼金',
            '退款',
            '其他'
        ] else array[
            'Salary',
            'Investments',
            'Gifts',
            'Refunds',
            'Other'
        ] end
    ) with ordinality as t(name, ord)
    order by ord;

    return new;
end;
$$;

-- `create or replace` resets the grants; same lockdown as 20260910130400.
revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- --- rename_category ---------------------------------------------------------
-- Replaces 20260910130200's version, only so the list it hands back is in the
-- same order the app shows. The rename itself leaves sort_order alone.
create or replace function public.rename_category(
    p_kind     text,
    p_old_name text,
    p_new_name text
)
returns setof public.categories
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_old text := btrim(coalesce(p_old_name, ''));
    v_new text := btrim(coalesce(p_new_name, ''));
    v_id  uuid;
begin
    if p_kind not in ('expense', 'income') then
        raise exception 'Category type must be expense or income'
            using errcode = 'check_violation';
    end if;

    select id into v_id
      from public.categories
     where user_id = (select auth.uid()) and kind = p_kind and name = v_old;

    if v_id is null then
        raise exception 'Category % not found', v_old using errcode = 'no_data_found';
    end if;

    -- The remaining validations (blank, over 40 characters, the reserved word
    -- 'Transfer', and case-insensitive collision) are table constraints, so
    -- this UPDATE raises on its own if the new name breaks any of them.
    update public.categories set name = v_new where id = v_id;

    -- Cascade. `type = p_kind` mirrors the old WHERE clause: an expense
    -- category rename must not touch an income row that happens to share a name.
    update public.transactions
       set category = v_new
     where user_id = (select auth.uid()) and category = v_old and type = p_kind;

    -- Subscriptions are expenses only, as in the Python.
    if p_kind = 'expense' then
        update public.subscriptions
           set category = v_new
         where user_id = (select auth.uid()) and category = v_old;
    end if;

    return query
        select * from public.categories
         where user_id = (select auth.uid()) order by kind, sort_order;
end;
$$;
